'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NanoReportParam

    '''<summary>
    '''lblParameterName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParameterName As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''panelContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelContent As Global.DevExpress.Web.ASPxPanel

    '''<summary>
    '''dateTimeDIV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateTimeDIV As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''comboDateSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comboDateSelected As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''odsDateTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDateTypes As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''dateSpecificDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateSpecificDate As Global.DevExpress.Web.ASPxDateEdit
End Class
