'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReportScheduler_test

    '''<summary>
    '''gvreportScheduler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvreportScheduler As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''odsSubscribers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSubscribers As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsReportTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsReportTypes As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsDaysOfMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDaysOfMonth As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsDaysOfWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDaysOfWeek As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsReports As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsReportSchedules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsReportSchedules As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
