'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AlarmsAndEvents

    '''<summary>
    '''ASPxPageControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPageControl1 As Global.DevExpress.Web.ASPxPageControl

    '''<summary>
    '''ASPxGridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView1 As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''odsEventConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsEventConfiguration As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsVehicles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsVehicles As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsMetric control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsMetric As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''txtSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearch As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''gvEventOccurances control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvEventOccurances As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''odsEventOccurances control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsEventOccurances As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''gvAlertConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAlertConfiguration As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''odsAlertConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsAlertConfiguration As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsEventType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsEventType As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsMessageDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsMessageDestination As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
