'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReportScheduler

    '''<summary>
    '''ASPxPageControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPageControl1 As Global.DevExpress.Web.ASPxPageControl

    '''<summary>
    '''dgvReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvReports As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''odsReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsReports As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsReportList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsReportList As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSchedule As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsDaysOfWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDaysOfWeek As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsDaysOfMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDaysOfMonth As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsAVDTVehicles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsAVDTVehicles As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsSubscribers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSubscribers As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsReportTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsReportTypes As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsReport1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsReport1 As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
