'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TimeZoneTester

    '''<summary>
    '''cboPossibleTimeZones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPossibleTimeZones As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''dgvTimezoneSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvTimezoneSettings As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''odsAllTimeZoneOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsAllTimeZoneOptions As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsTimeZoneData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsTimeZoneData As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
