'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Test
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ASPxPageControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPageControl1 As Global.DevExpress.Web.ASPxPageControl
    
    '''<summary>
    '''dgvUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvUsers As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''btnDelete_Users control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete_Users As Global.DevExpress.Web.GridViewCommandColumnCustomButton
    
    '''<summary>
    '''odsRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRoles As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dgvRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvRoles As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''btnDelete_Roles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete_Roles As Global.DevExpress.Web.GridViewCommandColumnCustomButton
    
    '''<summary>
    '''odsRolesUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRolesUsers As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsRolesRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRolesRoles As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsFeatures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsFeatures As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''ASPxGridView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView2 As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''dgvRoleAccessToFeatures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvRoleAccessToFeatures As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''btnDelete_RolesAccessFeature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete_RolesAccessFeature As Global.DevExpress.Web.GridViewCommandColumnCustomButton
    
    '''<summary>
    '''odsApplicationFeatureRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsApplicationFeatureRoles As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsAppFeatRoleFeatures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsAppFeatRoleFeatures As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsAppFeatRoleRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsAppFeatRoleRoles As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''ASPxLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel1 As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''imgCompanylogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCompanylogo As Global.DevExpress.Web.ASPxBinaryImage
    
    '''<summary>
    '''ASPxButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton1 As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''ASPxLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel2 As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''dgvSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvSettings As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''ASPxLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel5 As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''ASPxLabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel6 As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''cboDefaultBusinessLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDefaultBusinessLocation As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''ASPxLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel3 As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''cboPossibleTimeZones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPossibleTimeZones As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''dgvTimezoneSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvTimezoneSettings As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''dgvBusinessLocations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvBusinessLocations As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''btnDelete_BusinessLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete_BusinessLocation As Global.DevExpress.Web.GridViewCommandColumnCustomButton
    
    '''<summary>
    '''odsApplicationLocations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsApplicationLocations As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsHomeImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsHomeImages As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''ASPxLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel4 As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''ASPxPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPanel1 As Global.DevExpress.Web.ASPxPanel
    
    '''<summary>
    '''ASPxButtonHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButtonHome As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''ASPxButtonVehicle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButtonVehicle As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''ASPxHiddenFieldUpdateType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxHiddenFieldUpdateType As Global.DevExpress.Web.ASPxHiddenField
    
    '''<summary>
    '''cpDeleteImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpDeleteImage As Global.DevExpress.Web.ASPxCallback
    
    '''<summary>
    '''dvGalery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvGalery As Global.DevExpress.Web.ASPxDataView
    
    '''<summary>
    '''odsMapMarker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsMapMarker As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''ASPxBinaryImageBrowse1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxBinaryImageBrowse1 As Global.DevExpress.Web.ASPxBinaryImage
    
    '''<summary>
    '''ASPxButtonBrowse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButtonBrowse As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''ASPxButton3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton3 As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''odsAllTimeZoneOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsAllTimeZoneOptions As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsTimeZoneData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsTimeZoneData As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsUsers As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSettings As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsTimeZonesForUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsTimeZonesForUsers As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsApplicationLocationsWithDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsApplicationLocationsWithDefault As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsVehicles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsVehicles As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''DeleteDialog_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_User As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_User As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_User As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''DeleteDialog_Roles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_Roles As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_Roles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_Roles As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_Roles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_Roles As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''DeleteDialog_RolesAccessFeature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_RolesAccessFeature As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_RolesAccessFeature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_RolesAccessFeature As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_RolesAccessFeature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_RolesAccessFeature As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''DeleteDialog_BusinessLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_BusinessLocation As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_BusinessLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_BusinessLocation As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_BusinessLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_BusinessLocation As Global.DevExpress.Web.ASPxButton
End Class
