'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ClientAssignments
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''FleetManagementPageControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FleetManagementPageControl As Global.DevExpress.Web.ASPxPageControl
    
    '''<summary>
    '''RunGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RunGridView As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''odsTblRuns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsTblRuns As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRun As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsRunMultiDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRunMultiDocs As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsRunsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRunsList As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsDriverList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDriverList As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''ClientGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientGridView As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''odsSites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSites As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsClient As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsMultiDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsMultiDocs As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsCustomerList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsCustomerList As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''GetRunsForAssignmentGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetRunsForAssignmentGridView As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''odsGetRunsForAssignment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsGetRunsForAssignment As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsTblDrivers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsTblDrivers As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''RunSiteGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RunSiteGridView As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''odsRunSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRunSite As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
