'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ClientAssignments
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''FleetManagementPageControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FleetManagementPageControl As Global.DevExpress.Web.ASPxPageControl
    
    '''<summary>
    '''cbFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbFields As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''btnCollapse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCollapse As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''btnExpand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExpand As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''RunGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RunGridView As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''btnDelete_Run control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete_Run As Global.DevExpress.Web.GridViewCommandColumnCustomButton
    
    '''<summary>
    '''odsTblRuns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsTblRuns As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRun As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsRunMultiDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRunMultiDocs As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsRunsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRunsList As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsDriverList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDriverList As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''hdnStoreCid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStoreCid As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''SiteDetailsGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SiteDetailsGridView As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''btnDelete_SiteTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete_SiteTab As Global.DevExpress.Web.GridViewCommandColumnCustomButton
    
    '''<summary>
    '''viewPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewPopup As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.DevExpress.Web.ASPxPanel
    
    '''<summary>
    '''odsDrivers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDrivers As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsReason As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsServiceFrequency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsServiceFrequency As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsServiceRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsServiceRun As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsFrequency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsFrequency As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsServices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsServices As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsRateIncrease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRateIncrease As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsInvoiceMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsInvoiceMonth As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsInvoiceFrequency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsInvoiceFrequency As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsSiteCeaseReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSiteCeaseReason As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsInitialContractPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsInitialContractPeriod As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsSalesPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSalesPerson As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsPreviousSuppliers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsPreviousSuppliers As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsIndustryGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsIndustryGroups As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsCustomers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsCustomers As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsZones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsZones As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsStates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsStates As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsSiteDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSiteDetails As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsSites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSites As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsMultiDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsMultiDocs As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''GetRunsForAssignmentGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetRunsForAssignmentGridView As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''odsGetRunsForAssignment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsGetRunsForAssignment As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsTblDrivers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsTblDrivers As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''RunSiteGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RunSiteGridView As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''btnDelete_RunSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete_RunSite As Global.DevExpress.Web.GridViewCommandColumnCustomButton
    
    '''<summary>
    '''odsRunSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRunSite As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''gvRunCompletion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRunCompletion As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''odsRunCompletion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRunCompletion As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''DeleteDialog_SiteDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_SiteDetail As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_SiteDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_SiteDetail As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_SiteDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_SiteDetail As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''DeleteDialog_RunDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_RunDoc As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_RunDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_RunDoc As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_RunDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_RunDoc As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''DeleteDialog_RunSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_RunSite As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_RunSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_RunSite As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_RunSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_RunSite As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''DeleteDialog_SiteTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_SiteTab As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_SiteTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_SiteTab As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_SiteTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_SiteTab As Global.DevExpress.Web.ASPxButton
End Class
