'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DriverDetails
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ASPxLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel1 As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''gvDriver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDriver As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''deleteButton_Main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deleteButton_Main As Global.DevExpress.Web.GridViewCommandColumnCustomButton
    
    '''<summary>
    '''btnComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnComment As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''btnAllocate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAllocate As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''pupComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pupComment As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''lblComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComment As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''gvDriverCommentReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDriverCommentReason As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''btnDelete_CommentReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete_CommentReason As Global.DevExpress.Web.GridViewCommandColumnCustomButton
    
    '''<summary>
    '''btnCloseComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseComments As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''pupAllocate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pupAllocate As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''ASPxLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel2 As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''ASPxLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel3 As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''cboDriverFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDriverFrom As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''ASPxLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel4 As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''cboDriverTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDriverTo As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''btnChangeRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChangeRun As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''btnCloseAllocate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseAllocate As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''DeleteDialog_Main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_Main As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_Main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_Main As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_Main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_Main As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''DeleteDialog_Comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_Comments As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_Comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_Comments As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_Comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_Comments As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''DeleteDialog_CommentReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_CommentReason As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_CommentReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_CommentReason As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_Bookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_Bookings As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''odsDriver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDriver As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsDriverComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDriverComments As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsDriverCommentsReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDriverCommentsReason As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsAllocateDriverFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsAllocateDriverFrom As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsAllocateDriverTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsAllocateDriverTo As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
