'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SiteDetailsMain
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''hdnStoreCid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStoreCid As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''SiteDetailsGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SiteDetailsGridView As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''btnDelete_SiteDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete_SiteDetail As Global.DevExpress.Web.GridViewCommandColumnCustomButton
    
    '''<summary>
    '''viewPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewPopup As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.DevExpress.Web.ASPxPanel
    
    '''<summary>
    '''DeleteDialog_SiteDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_SiteDetail As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_SiteDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_SiteDetail As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_SiteDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_SiteDetail As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''DeleteDialog_ResignHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_ResignHistory As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_ResignHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_ResignHistory As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_ResignHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_ResignHistory As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''DeleteDialog_SiteServices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_SiteServices As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_SiteServices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_SiteServices As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_SiteServices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_SiteServices As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''DeleteDialog_Comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteDialog_Comments As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''yesButton_Comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yesButton_Comments As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''noButton_Comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noButton_Comments As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''myAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myAlert As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.DevExpress.Web.ASPxPanel
    
    '''<summary>
    '''ASPxButton7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton7 As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''odsDrivers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDrivers As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsReason As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsServiceFrequency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsServiceFrequency As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsServiceRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsServiceRun As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsFrequency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsFrequency As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsServices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsServices As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsRateIncrease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRateIncrease As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsInvoiceMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsInvoiceMonth As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsInvoiceFrequency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsInvoiceFrequency As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsSiteCeaseReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSiteCeaseReason As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsInitialContractPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsInitialContractPeriod As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsSalesPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSalesPerson As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsPreviousSuppliers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsPreviousSuppliers As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsIndustryGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsIndustryGroups As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsCustomers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsCustomers As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsZones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsZones As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsStates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsStates As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsSiteDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSiteDetails As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
