'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CannonFleetManagement

    '''<summary>
    '''CannonFleetManagementPageControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CannonFleetManagementPageControl As Global.DevExpress.Web.ASPxPageControl

    '''<summary>
    '''DocumentGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocumentGridView As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''odsDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDocuments As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''RunGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RunGridView As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''odsRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRun As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''ClientGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientGridView As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''odsClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsClient As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''DriverGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DriverGridView As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''odsDriver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDriver As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''RunCompletionGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RunCompletionGridView As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''odsRunCompletion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRunCompletion As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''RunClientGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RunClientGridView As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''odsRunClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRunClient As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
