'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SiteDetailsMain

    '''<summary>
    '''hdnStoreCid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStoreCid As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''SiteDetailsGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SiteDetailsGridView As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''viewPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewPopup As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.DevExpress.Web.ASPxPanel

    '''<summary>
    '''odsServices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsServices As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsRateIncrease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRateIncrease As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsInvoiceMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsInvoiceMonth As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsInvoiceFrequency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsInvoiceFrequency As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsSiteCeaseReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSiteCeaseReason As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsInitialContractPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsInitialContractPeriod As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsSalesPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSalesPerson As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsPreviousSuppliers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsPreviousSuppliers As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsIndustryGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsIndustryGroups As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsCustomers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsCustomers As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsZones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsZones As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsStates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsStates As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsSiteDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSiteDetails As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
